// Generated by Wrangler by running `wrangler types`

interface Env {
	OPEN_AI_APIKEY: string;
	RESEND_APIKEY: string;
	SIGNALWIRE_APIKEY: string;
	DO: DurableObjectNamespace<import("./src/index").CALL_SESSION>;
}
